# Generated by Django 2.1.7 on 2019-05-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('sdg', 'ГСС'), ('tg', 'УТГ'), ('itg1', 'ГНП-1'), ('itg2', 'ГНП-2'), ('wg', 'ГВД')], max_length=16)),
            ],
        ),
    ]
